export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_SUMMARIES = 'FETCH_POST_SUMMARIES';

export const SET_WINDOW_DIMENSIONS = 'SET_WINDOW_DIMENSIONS';
export const SET_SCROLL = 'SET_SCROLL';
export const SET_LOADED_IMAGE = 'SET_LOADED_IMAGE';

export const SET_URL = 'SET_URL';
